config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
       resources :comments, only: [:create, :destroy]
       resources :likes, only: [:create]
    end
  end

  namespace :api, defaults: { format: :json} do
    post 'users/register', to: 'authentication#register'
    post 'users/login', to: 'authentication#login'
    get 'posts', to: 'api#posts_index'
    get 'comments', to: 'api#list_comments'
    post 'new_comment', to: 'api#create_comment'
  end

  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :posts
  has_many :comments
  has_many :likes, foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  def last_three
    posts.order(created_at: :desc).limit(3)
  end

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.last_three
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<ul class="m-5vw">
<% @users.each do |user| %>
    <li class="flex-container mb-5vh border-solid">
        <% if user.photo.nil? %>
        <%= image_tag("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", :class => "w-15")%>
        <% else %>
         <%= image_tag(user.photo, :class => "w-15")%>
        <% end %>
        <div class="flex-container flex-col m-20 space-btw w-100">
          <h2><%=link_to user.name, user%></h2>
          <p class="align-right">Number of posts: <%= user.postsCounter%></p>
        </div>
    <li>
<% end %>
<ul>

app/views/users/show.html.erb
<div class="m-5vw">

<% if current_user %>
<%= render "shared/user" %>

<div class="border-solid">
  <h3 class="m-20">Bio</h3>
  <p class="m-20"><%= @user.bio %></p>
</div>

<ul class="mt-15px">
    <% @posts.each do |post|%>
        <li class="flex-container flex-col mb-5vh border-solid p-20">
          <h4><%= link_to post.title, user_post_path(user_id: @user.id, id:post.id)%></h4>
          <div class="flex-container flex-col w-100 mt-15px">
            <p> <%= post.text %> </p>
            <p class="align-right font-sm">Comments: <%=post.commentCounter%>, Likes: <%=post.likesCounter%></p>
          </div>
        </li>
        <% if can? :destroy, post %>
          <%= button_to "Delete Post", user_post_path(user_id: current_user.id, post_id: post.id), method: :delete %>
        <% end %>
    <% end %>
</ul>

<div class="flex-container">
  <button class="mt-15px mb-5vh mr-5vw"><%= link_to "See All Posts", user_posts_path(@user.id), :class => "decoration-none" %></button>
  <%= button_to "Log out", destroy_user_session_path, method: :delete, :class => "decoration-none mt-15px mb-5vh mr-5vw" %>
  <%= button_to "Edit Profile", user_registration_path, method: :patch, :class => "decoration-none mt-15px mb-5vh" %>
</div>
<%= render "posts/form" %>

<% else %>
  <h3>New here?</h3>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>
</div>