config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
       resources :comments, only: [:create, :destroy]
       resources :likes, only: [:create]
    end
  end

  namespace :api, defaults: { format: :json} do
    post 'users/register', to: 'authentication#register'
    post 'users/login', to: 'authentication#login'
    get 'posts', to: 'api#posts_index'
    get 'comments', to: 'api#list_comments'
    post 'new_comment', to: 'api#create_comment'
  end

  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_counter

  validates :title, presence: true, length: { in: 1..250 }
  validates :commentCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  def update_counter
    user = User.find(user_id)
    user.increment!(:postsCounter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.all.where("post_id = #{params[:id]}")
    @comment = Comment.all.where("post_id = #{params[:id]}, user_id = #{params[:user_id]}")
  end

  def create
    @user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_path(@user), notice: 'Post added successfully!'
    else
      flash.now[:notice] = 'Post could not be created'
      render 'users/show'
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    post.destroy

    redirect_to user_path, notice: 'Post is deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2 class="mb-2vh">Write a new post:</h2>
<%= form_with model: [ current_user, current_user.posts.build] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    <p>
      <%= form.submit "Add Post" %>
    </p>
  <% end %>

app/views/posts/index.html.erb
<div class="m-5vw">

<%= render "shared/user" %>

<ul>
    <% @posts.each do |post| %>
        <li class="flex-container mb-5vh flex-col">
          <div class="border-solid flex-container flex-col space-between p-20">
            <h3 class="mb-5vh"><%= link_to post.title, user_post_path(id:post.id)%></h3>
            <p><%= post.text %></p>
            <p class="align-right font-sm">Comments: <%=post.commentCounter%> , Likes: <%= post.likesCounter %> </p>
          </div>
            <ul class="border-solid mt-15px p-20">
            <% if post.comments.empty? %> <li>There aren't any comments here yet, be the first to write a comment!</li>
            <% else post.comments.each do |comment|  %>
                <li><%= User.find(comment.user_id).name %>: <%=comment.text %><li>
            <% end %>
            <% end %>
            </ul>
        </li>
    <% end %>
</ul>

<%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="m-5vw">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>

  <div class="border-solid p-20 flex-container flex-col mb-2vh">
    <h3><%=@post.title%> by <%=@user.name%></h3>
    <p class="align-right font-sm"> Comments: <%=@post.commentCounter%>, Likes: <%= @post.likesCounter%></p>
    <p><%=@post.text%></p>
  </div>

  <%= button_to 'Like this post', user_post_likes_path(@user, @post), method: :post %>

  <ul class="border-solid p-20 mt-15px mb-5vh">
    <% if @comments.empty? %> <li>There aren't any comments here yet, be the first to write a comment! </li>
    <% else @comments.each do |comment| %>
        <li>
          <%= User.find(comment.user_id).name %>: <%=comment.text %>
        <% if can? :destroy, comment %>
          <%= button_to "Delete Comment", user_post_comment_path(user_id: current_user.id, post_id: @post.id, id:comment.id), method: :delete %>
        <% end %>
        </li>
    <% end %>
    <% end %>
  </ul>

<%= render "comments/form" %>
</div>